# Generated by Django 3.0.3 on 2020-02-11 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='Quantity',
            new_name='Mobile_no',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='Choice',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='Customize',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='Type',
        ),
    ]
