# Generated by Django 3.0.3 on 2020-02-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20200211_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='Name',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='Mobile_no',
            new_name='mobile_no',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='customize',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
