# Generated by Django 3.0.3 on 2020-02-12 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_auto_20200211_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
